### ISSUE TITLE
Non-deterministic error in bound plate

### ISSUE THREAD

**Issue by ThomasHeap** [alan-ppl/alan#11]
These lines won't always return ```extra_plate_shape``` in the same order, leading to an error which occurs randomly!

https://github.com/alan-ppl/alan/blob/40e94bd96ef4dec3cb38bba44d5bc7bfde60b24b/src/alan/BoundPlate.py#L30-L32

Example that causes this:

```python
import torch as t
from alan import Normal, Bernoulli, Beta, Binomial, Plate, BoundPlate, Problem, Data, mean, OptParam, QEMParam, checkpoint, no_checkpoint, Split

platesizes = {'species':22, 'sites':16}

P_plate = Plate( 
        alpha = Normal(0.,2.5),
        beta = Normal(0.,2.5),
        log_sigma = Normal(0.,1),
        Sigma = Beta(2.,2.),
        species = Plate(
            u = Normal(0, lambda log_sigma: log_sigma.exp()),
            v = Normal(0, lambda log_sigma: log_sigma.exp()),
            w = Bernoulli(logits='Sigma'),
            sites = Plate(
                z = Bernoulli(logits=lambda u, alpha: u + alpha),
                y = Binomial(total_count=18, logits=lambda z,v,beta: z * (v+beta)),
            ),
        ),   
    )


Q_plate = Plate(
            alpha = Normal(OptParam(0.), OptParam(1., transformation=t.exp)),
            beta = Normal(OptParam(0.), OptParam(1., transformation=t.exp)),
            log_sigma = Normal(OptParam(0.), OptParam(1., transformation=t.exp)),
            Sigma = Beta(OptParam(2.), OptParam(2.)),
            species = Plate(
                u = Normal(OptParam(0.), OptParam(1., transformation=t.exp)),
                v = Normal(OptParam(0.), OptParam(1., transformation=t.exp)),
                w = Bernoulli(logits=OptParam(0.)),
                sites = Plate(
                    z = Bernoulli(logits=OptParam(0.)),
                    y = Data()
                ),
            ),
        )

P_bound_plate = BoundPlate(P_plate, platesizes)
Q_bound_plate = BoundPlate(Q_plate, platesizes)
```
will sometimes return:

```
Traceback (most recent call last):
  File "/home/thomas/Work/alan/examples/examples/occupancy_minimal.py", line 45, in <module>
    Q_bound_plate = BoundPlate(Q_plate, platesizes)
  File "/home/thomas/Work/alan/src/alan/BoundPlate.py", line 225, in __init__
    self.sample()
  File "/home/thomas/Work/alan/src/alan/BoundPlate.py", line 374, in sample
    torchdim_tree_withK, _ = self._sample(1, False, PermutationSampler, all_platedims)
  File "/home/thomas/Work/alan/src/alan/BoundPlate.py", line 357, in _sample
    inputs_params=self.inputs_params(all_platedims),
  File "/home/thomas/Work/alan/src/alan/BoundPlate.py", line 307, in inputs_params
    return named2torchdim_flat2tree(self.inputs_params_flat_named(), all_platedims, self.plate)
  File "/home/thomas/Work/alan/src/alan/BoundPlate.py", line 14, in named2torchdim_flat2tree
    flat_torchdim = named2dim_dict(flat_named, all_platedims)
  File "/home/thomas/Work/alan/src/alan/utils.py", line 136, in named2dim_dict
    raise Exception(f"Dimension size mismatch along {dimname} in tensor {varname} in {setting}.  Specifically, the size provided in all_platesizes is {dim.size}, while the size of the tensor along this dimension is {tensor.size(dimname)}.")
Exception: Dimension size mismatch along species in tensor z_logits in .  Specifically, the size provided in all_platesizes is 22, while the size of the tensor along this dimension is 16.
```

**Comment by sambowyer** [comment]
Fixed by avoiding use of sets.

https://github.com/alan-ppl/alan/blob/ae1a6fcfdc45cac6081f32c9611382bf69b62a57/src/alan/BoundPlate.py#L29
