### ISSUE TITLE
Named params

### ISSUE THREAD

**Issue by ThomasHeap** [alan-ppl/alan#2]
I seem to get the following error whenever I have OptParams within a plate:

```
Traceback (most recent call last):
  File "/home/thomas/Work/alan/examples/examples/minimal.py", line 44, in <module>
    opt.step()
  File "/home/thomas/anaconda3/envs/alan_simp/lib/python3.10/site-packages/torch/optim/optimizer.py", line 379, in wrapper
    out = func(*args, **kwargs)
  File "/home/thomas/anaconda3/envs/alan_simp/lib/python3.10/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/thomas/anaconda3/envs/alan_simp/lib/python3.10/site-packages/torch/optim/adam.py", line 166, in step
    adam(
  File "/home/thomas/anaconda3/envs/alan_simp/lib/python3.10/site-packages/torch/optim/adam.py", line 316, in adam
    func(params,
  File "/home/thomas/anaconda3/envs/alan_simp/lib/python3.10/site-packages/torch/optim/adam.py", line 391, in _single_tensor_adam
    exp_avg.lerp_(grad, 1 - beta1)
RuntimeError: aten::lerp_.Scalar is not yet supported with named tensors. Please drop names via `tensor = tensor.rename(None)`, call the op with an unnamed tensor, and set names on the result of the operation.
```

This is because the parameters will have its dimensions named according to the plates. Should parameters have torchdims instead? The naming happens here: https://github.com/alan-ppl/alan/blob/c3848d123e2c1f38a61e393798919d00fff8252d/src/alan/BoundPlate.py#L17

**Comment by ThomasHeap** [comment]
Example to reproduce:

```python
import torch as t
from alan import Normal, Plate, BoundPlate, Problem, Data, checkpoint, OptParam

computation_strategy = checkpoint

P = Plate(
    mu = Normal(t.zeros((2,)), t.ones((2,))), 
    p1 = Plate(
        theta = Normal('mu', t.ones((2,))),
        obs = Normal("mu", t.ones((2,)))
    )
)
    
Q = Plate(
    mu = Normal(OptParam(0.), t.ones((2,))),
    p1 = Plate(
        theta = Normal(OptParam(0.), t.ones((2,))),
        obs = Data()
    )
)


platesizes = {'p1': 3}
data = {'obs': t.randn((3,2), names=('p1', None))}

P = BoundPlate(P, platesizes)
Q = BoundPlate(Q, platesizes)

prob = Problem(P, Q, data)

opt = t.optim.Adam(prob.parameters(), lr=1e-3)

for param in prob.parameters():
    if param.requires_grad:
        print(param.data)
        
K = 10
print("K={}".format(K))
for i in range(1000):
    opt.zero_grad()
    sample = prob.sample(K=K)
    elbo = sample.elbo_vi(computation_strategy=computation_strategy)
    elbo.backward()
    opt.step()

    if 0 == i%200:
        print(elbo.item())
```

**Comment by LaurenceA** [comment]
Our code works right (it is supposed to switch between named and torchdim tensors).  The problem is that PyTorch is failing for named tensors.  This is annoying but relatively easily fixable (I'll get round to it this afternoon or tomorrow morning).

**Comment by LaurenceA** [comment]
Should be sorted!

**Comment by ThomasHeap** [comment]
This error is still occuring with named params in ``extra_opt_params``

```python
import torch as t
import torch.nn as nn
from alan import Normal, Plate, BoundPlate, Group, Problem, Data, mean, Split, OptParam, QEMParam, checkpoint, no_checkpoint, Split


t.manual_seed(0)

device = 'cpu'

computation_strategy = checkpoint 

P_plate = Plate( 
    mu = Normal(0, 1),
    p1 = Plate(
        theta = Normal('mu', 1),
        obs = Normal('mu', 1),
    ),
)

plate_sizes = {'p1': 3}
P_bound_plate = BoundPlate(P_plate, plate_sizes)

Q_plate = Plate( 
    mu = Normal(0, 1),
    p1 = Plate(
        theta = Normal('theta_loc', 1),
        obs = Data(),
    ),
)

Q_bound_plate = BoundPlate(Q_plate, plate_sizes, extra_opt_params = {"theta_loc": t.zeros((3,), names = ('p1',))})

P_sample = P_bound_plate.sample()
data = {'obs': P_sample['obs']}

problem = Problem(P_bound_plate, Q_bound_plate, data)
#Move problem to the device.
problem.to(device=device)


opt = t.optim.Adam(problem.parameters(), lr=1e-3)

K=1
print("K={}".format(K))
for i in range(1000):
    opt.zero_grad()
    sample = problem.sample(K=K)
    elbo = sample.elbo_vi(computation_strategy=computation_strategy)
    elbo.backward()
    opt.step()

    if 0 == i%200:
        print(elbo.item())
```

Gives the same error:

```
RuntimeError: aten::lerp_.Scalar is not yet supported with named tensors. Please drop names via `tensor = tensor.rename(None)`, call the op with an unnamed tensor, and set names on the result of the operation.
```

**Comment by LaurenceA** [comment]
I managed to break it as I was simplifying the fix.

Should be working now.
