### ISSUE TITLE
Specifying sample shape not working for QEM Parameter

### ISSUE THREAD

**Issue by ThomasHeap** [alan-ppl/alan#7]
The user needs to explicitly give arguments to QEM of the right shape and can't just specify sample shape

```python
import torch as t
from alan import Normal, Plate, BoundPlate, Problem, Data, checkpoint, OptParam, QEMParam

computation_strategy = checkpoint

P = Plate(
    mu = Normal(t.zeros((2,)), t.ones((2,)), sample_shape = t.Size([2])), 
    p1 = Plate(

        obs = Normal("mu", t.ones((2,)))
    )
)
    
Q = Plate(
    mu = Normal(QEMParam(0.), QEMParam(1.), sample_shape = t.Size([2])),
    p1 = Plate(
        obs = Data()
    )
)


platesizes = {'p1': 3}


P = BoundPlate(P, platesizes)
Q = BoundPlate(Q, platesizes)

P_sample = P.sample()
data = {'obs': P_sample['obs']}

prob = Problem(P, Q, data)

sample = prob.sample(K=10)
sample.update_qem_params(0.01)
```

This fails with:

```
Traceback (most recent call last):
  File "/home/thomas/Work/alan/examples/examples/test.py", line 34, in <module>
    sample.update_qem_params(0.01)
  File "/home/thomas/Work/alan/src/alan/Sample.py", line 352, in update_qem_params
    self.problem.Q._update_qem_params(lr, self, computation_strategy=computation_strategy)
  File "/home/thomas/Work/alan/src/alan/BoundPlate.py", line 302, in _update_qem_params
    self._update_qem_moving_avg(lr, sample, computation_strategy)
  File "/home/thomas/Work/alan/src/alan/BoundPlate.py", line 297, in _update_qem_moving_avg
    assert (prev_moment.names == new_moment.names)
AssertionError
```

To fix replace

```python
mu = Normal(QEMParam(0.), QEMParam(1.), sample_shape = t.Size([2])),
```

with

```python
mu = Normal(QEMParam(t.zeros((2,))), QEMParam(t.ones((2,)))
```

**Comment by LaurenceA** [comment]
The QEM parameters are initialized to `t.zeros(())` and `t.ones(())`, rather than `t.zeros(2)` and `t.ones(2)` as desired.

Trying to get the "broadcasting" behaviour here is probably a bad idea, as we should have the same behaviour for QEMParam as OptParam, and we can't automatically get the user dimensions of OptParam right, because the user-dimensions might arise through another input (and not sample_sample).

So we probably want to have appropriate errors for:
`mu = Normal(QEMParam(0.), QEMParam(1.), sample_shape = t.Size([2]))`
We could ban / warn for `sample_shape` combined with opt_param.  In that case, it would make sense to delete stuff around missing out plates in QEMParam (which likely doesn't work, and I can't see a use for it).

**Comment by ThomasHeap** [comment]
This should be addressed in ffaadb74639e8d9bff194e3e1957b9603d5c5d54 but where is the stuff about missing out plates in QEMParam?
